In [213]:
import json

candidates = []

with open("candidates.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        if line.strip():
            candidates.append(json.loads(line))

print("Number of candidates:", len(candidates))

Number of candidates: 100000

In [214]:
candidates[0]

{'candidate_id': 'CAND_0000001',
 'profile': {'anonymized_name': 'Ira Vora',
  'headline': 'Backend Engineer | SQL, Spark, Cloud',
  'summary': "Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.",
  'location': 'Toronto',
  'country': 'Canada',
  'years_of_experience': 6.9,
  'current_title': 'Backend Engineer',
  'current_company': 'Mindtree',
  'current_company_size': '10001+',
  'current_industry': 'IT Services'},
 'career_history': [{'company': 'Mindtree',
   'title': 'Backend Engineer',
   'start_date': '2024-03-08',
   'end_date': None,
   'duration_months': 27,
   'is_current': True,
   'industry': 'IT Services',
   'company_size': '10001+',
   'description': 'Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.'},
  {'company': 'Dunder Mifflin',
   'title': 'Analytics Engineer',
   'start_date': '2019-07-03',
   'end_date': '2024-01-08',
   'duration_months': 55,
   'is_current': False,
   'industry': 'Paper Products',
   'company_size': '201-500',
   'description': 'Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.'}],
 'education': [{'institution': 'Lovely Professional University',
   'degree': 'B.E.',
   'field_of_study': 'Computer Science',
   'start_year': 2017,
   'end_year': 2020,
   'grade': '8.24 CGPA',
   'tier': 'tier_3'}],
 'skills': [{'name': 'Tailwind',
   'proficiency': 'intermediate',
   'endorsements': 3,
   'duration_months': 13},
  {'name': 'NLP',
   'proficiency': 'advanced',
   'endorsements': 37,
   'duration_months': 26},
  {'name': 'Image Classification',
   'proficiency': 'advanced',
   'endorsements': 7,
   'duration_months': 40},
  {'name': 'Fine-tuning LLMs',
   'proficiency': 'advanced',
   'endorsements': 21,
   'duration_months': 36},
  {'name': 'Weights & Biases',
   'proficiency': 'intermediate',
   'endorsements': 13,
   'duration_months': 30},
  {'name': 'Speech Recognition',
   'proficiency': 'advanced',
   'endorsements': 52,
   'duration_months': 33},
  {'name': 'Photoshop',
   'proficiency': 'intermediate',
   'endorsements': 8,
   'duration_months': 24},
  {'name': 'TTS',
   'proficiency': 'advanced',
   'endorsements': 56,
   'duration_months': 60},
  {'name': 'LoRA',
   'proficiency': 'intermediate',
   'endorsements': 0,
   'duration_months': 28},
  {'name': 'Apache Beam',
   'proficiency': 'intermediate',
   'endorsements': 4,
   'duration_months': 9},
  {'name': 'AWS',
   'proficiency': 'beginner',
   'endorsements': 5,
   'duration_months': 8},
  {'name': 'Flask',
   'proficiency': 'beginner',
   'endorsements': 15,
   'duration_months': 15},
  {'name': 'BentoML',
   'proficiency': 'intermediate',
   'endorsements': 3,
   'duration_months': 36},
  {'name': 'Milvus',
   'proficiency': 'advanced',
   'endorsements': 40,
   'duration_months': 35},
  {'name': 'GANs',
   'proficiency': 'advanced',
   'endorsements': 12,
   'duration_months': 19},
  {'name': 'Statistical Modeling',
   'proficiency': 'intermediate',
   'endorsements': 9,
   'duration_months': 8},
  {'name': 'GCP',
   'proficiency': 'beginner',
   'endorsements': 7,
   'duration_months': 2}],
 'certifications': [],
 'languages': [{'language': 'English', 'proficiency': 'professional'},
  {'language': 'Hindi', 'proficiency': 'conversational'}],
 'redrob_signals': {'profile_completeness_score': 86.9,
  'signup_date': '2025-10-16',
  'last_active_date': '2026-05-20',
  'open_to_work_flag': True,
  'profile_views_received_30d': 23,
  'applications_submitted_30d': 2,
  'recruiter_response_rate': 0.34,
  'avg_response_time_hours': 177.8,
  'skill_assessment_scores': {'NLP': 38.8,
   'Image Classification': 64.8,
   'Fine-tuning LLMs': 41.6,
   'Speech Recognition': 53.7},
  'connection_count': 356,
  'endorsements_received': 35,
  'notice_period_days': 60,
  'expected_salary_range_inr_lpa': {'min': 18.7, 'max': 36.1},
  'preferred_work_mode': 'onsite',
  'willing_to_relocate': False,
  'github_activity_score': 9.2,
  'search_appearance_30d': 249,
  'saved_by_recruiters_30d': 4,
  'interview_completion_rate': 0.71,
  'offer_acceptance_rate': 0.58,
  'verified_email': True,
  'verified_phone': True,
  'linkedin_connected': False}}

In [215]:
type(candidates[0])

dict

In [216]:
candidates[0].keys()

dict_keys(['candidate_id', 'profile', 'career_history', 'education', 'skills', 'certifications', 'languages', 'redrob_signals'])

In [217]:
pip install python-docx

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-docx in c:\users\manya\appdata\roaming\python\python313\site-packages (1.2.0)
Requirement already satisfied: lxml>=3.1.0 in c:\users\manya\appdata\roaming\python\python313\site-packages (from python-docx) (6.1.1)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\manya\appdata\roaming\python\python313\site-packages (from python-docx) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [218]:
from docx import Document

doc = Document("job_description.docx")

for para in doc.paragraphs:
    print(para.text)

Job Description: Senior AI Engineer — Founding Team
Company: Redrob AI (Series A AI-native talent intelligence platform)
Location: Pune/Noida, India (Hybrid — flexible cadence) | Open to relocation candidates from Tier-1 Indian cities
Employment Type: Full-time
Experience Required: 5–9 years (see "what we mean by this" below)

Let's be honest about this role
We're going to write this JD differently from most. We're a Series A company that just raised our round and we're building a new AI Engineering org from scratch. This is the kind of role where the JD changes every six months because the company changes every six months. So instead of pretending we have a fixed checklist, we're going to tell you what we actually need and what we've gotten wrong before.
If you've spent your career at Google or Meta and you want a well-scoped role with a defined ladder, this isn't it.
If you've spent your career bouncing between early-stage startups and you want to "just code" without having to think about product or recruiter workflows or eval frameworks, this also isn't it.
We need someone who is simultaneously comfortable with two things that sound contradictory:
Deep technical depth in modern ML systems — embeddings, retrieval, ranking, LLMs, fine-tuning.
Scrappy product-engineering attitude — willing to ship a working ranker in a week even if the underlying ML is "obviously suboptimal," because we need to learn from real users before we know what to actually optimize for.
These are not contradictory in real life. They feel contradictory because of how engineering culture sorted itself into "researcher" vs "shipper" archetypes. We need both modes available in the same person, and we'd rather you tilt slightly toward shipper than toward researcher.

What you'd actually be doing
The high-level mandate: own the intelligence layer of Redrob's product. That means the ranking, retrieval, and matching systems that decide what recruiters see when they search for candidates and what candidates see when they search for roles.
In practical terms, your first 90 days will probably look like:
Weeks 1-3: Audit what we currently have (it's mostly BM25 + rule-based scoring, working but not great). Identify the 3-4 highest-leverage things to fix.
Weeks 4-8: Ship a v2 ranking system that demonstrably improves recruiter-engagement metrics. This will involve embeddings, hybrid retrieval, and probably some LLM-based re-ranking, but the architecture is your call.
Weeks 9-12: Set up the evaluation infrastructure — offline benchmarks, online A/B testing, recruiter-feedback loops — so we can keep improving without flying blind.
Beyond that, you'll be driving the long-term architecture of how we do candidate-JD matching at scale, mentoring the next round of hires (we're growing the team from 4 to 12 engineers in the next year), and working closely with our recruiter-experience PM on what to build.

What we mean by "5-9 years"
This is a range, not a requirement. Some people hit "senior engineer" judgment at 4 years; some never hit it after 15. We've used 5-9 because it's roughly where people we've hired into this kind of role have landed, but we'll seriously consider candidates outside the band if other signals are strong.
That said, here are the disqualifiers we actually apply:
If you've spent your career in pure research environments (academic labs, research-only roles) without any production deployment — we will not move forward. We are explicit about this. We've tried it twice and it didn't work for either side.
If your "AI experience" consists primarily of recent (under 12 months) projects using LangChain to call OpenAI — we will probably not move forward, unless you can demonstrate substantial pre-LLM-era ML production experience. We're looking for people who understood retrieval and ranking before it became fashionable.
If you are a senior engineer who hasn't written production code in the last 18 months because you've moved into "architecture" or "tech lead" roles — we will probably not move forward. This role writes code.

The skills inventory (please read carefully)
Most JDs list 20 skills and you're supposed to have all of them. We're going to do this differently.
Things you absolutely need
Production experience with embeddings-based retrieval systems (sentence-transformers, OpenAI embeddings, BGE, E5, or similar) deployed to real users. We don't care which model — we care that you've handled embedding drift, index refresh, retrieval-quality regression in production.
Production experience with vector databases or hybrid search infrastructure — Pinecone, Weaviate, Qdrant, Milvus, OpenSearch, Elasticsearch, FAISS, or something similar. Again, the specific tech doesn't matter; the operational experience does.
Strong Python. Yes really, we care about code quality.
Hands-on experience designing evaluation frameworks for ranking systems — NDCG, MRR, MAP, offline-to-online correlation, A/B test interpretation. If you've never thought about how to evaluate a ranking system rigorously, this role will be very painful.
Things we'd like you to have but won't reject you for
LLM fine-tuning experience (LoRA, QLoRA, PEFT)
Experience with learning-to-rank models (XGBoost-based or neural)
Prior exposure to HR-tech, recruiting tech, or marketplace products
Background in distributed systems or large-scale inference optimization
Open-source contributions in the AI/ML space
Things we explicitly do NOT want
This is the section most JDs skip but we think it's the most important:
Title-chasers. If your career trajectory shows you optimizing for "Senior" → "Staff" → "Principal" titles by switching companies every 1.5 years, we're not a fit. We need someone who plans to be here for 3+ years.
Framework enthusiasts. If your GitHub is full of LangChain tutorials and your blog posts are "How I used [hot framework] to build [demo]" — that's fine but it's not what we need. We need people who think about systems, not frameworks.
People who have only worked at consulting firms (TCS, Infosys, Wipro, Accenture, Cognizant, Capgemini, etc.) in their entire career. We've had bad fit experiences in both directions. If you're currently at one of these companies but have prior product-company experience, that's fine.
People whose primary expertise is computer vision, speech, or robotics without significant NLP/IR exposure. We respect your work but you'd be re-learning fundamentals here.
People whose work has been entirely on closed-source proprietary systems for 5+ years without external validation (papers, talks, open-source). We need to see how you think, not just trust that you can think.

On location, comp, and logistics
Location: Pune/Noida-preferred but flexible. We have offices in Noida and Pune(mostly used Tue/Thu). We don't require any specific number of in-office days but we expect quarterly travel for offsites. Candidates in Hyderabad, Pune, Mumbai, Delhi NCR welcome to apply. Outside India: case-by-case, but we don't sponsor work visas.
Notice period: We'd love sub-30-day notice. We can buy out up to 30 days. 30+ day notice candidates are still in scope but the bar gets higher.

The vibe check
We genuinely believe culture-fit matters more at this stage than skills-fit. Skills are teachable; the rest mostly isn't.
We work async-first and write a lot. If you find writing painful, you'll find this role painful.
We disagree openly and decide quickly. If you find that style abrasive, you'll find this role abrasive.
We move fast and break things, with the caveat that "things" are usually our internal assumptions, not user-facing systems. If you need a stable, mature codebase to be productive, you'll find this role unstable.

How to read between the lines
The "ideal candidate" we're imagining is roughly:
6-8 years total experience, of which 4-5 are in applied ML/AI roles at product companies (not pure services).
Has shipped at least one end-to-end ranking, search, or recommendation system to real users at meaningful scale.
Has strong opinions about retrieval (hybrid vs dense), evaluation (offline vs online), and LLM integration (when to fine-tune vs prompt) — and can defend them with reference to systems they actually built.
Located in or willing to relocate to Noida or Pune.
Active on Redrob platform (or has clear signal of being in the job market) so we can actually talk to them.
We are aware this is a narrow profile. We're not expecting to find many matches in a 100K candidate pool. We're explicitly OK with that — we'd rather see 10 great matches than 1000 maybes.

Final note for the participants of the Redrob hackathon
If you're reading this in the context of the Intelligent Candidate Discovery & Ranking Challenge:
The "right answer" to this JD is not "find candidates whose skills section contains the most AI keywords." That's a trap we've explicitly built into the dataset.
The right answer involves reasoning about the gap between what the JD says and what the JD means. A Tier 5 candidate may not use the words "RAG" or "Pinecone" in their profile, but if their career history shows they built a recommendation system at a product company, they're a fit. A candidate who has all the AI keywords listed as skills but whose title is "Marketing Manager" is not a fit, no matter how perfect their skill list looks.
Your ranking system should also weigh behavioral signals — a perfect-on-paper candidate who hasn't logged in for 6 months and has a 5% recruiter response rate is, for hiring purposes, not actually available. Down-weight them appropriately.
Good luck.

In [ ]:
import pandas as pd

sample = pd.read_csv("sample_submission.csv")
sample.head()

,candidate_id,rank,score,reasoning
0,CAND_0004989,1,0.992,HR Manager with 6.1 yrs; 9 AI core skills; res...
1,CAND_0001195,2,0.984,HR Manager with 8.7 yrs; 9 AI core skills; res...
2,CAND_0003114,3,0.976,ML Engineer with 6.4 yrs; 4 AI core skills; re...
3,CAND_0000339,4,0.968,Content Writer with 8.3 yrs; 8 AI core skills;...
4,CAND_0001082,5,0.960,HR Manager with 5.0 yrs; 8 AI core skills; res...

In [220]:
sample.columns

Index(['candidate_id', 'rank', 'score', 'reasoning'], dtype='object')

In [221]:
candidates[0]["redrob_signals"]

{'profile_completeness_score': 86.9,
 'signup_date': '2025-10-16',
 'last_active_date': '2026-05-20',
 'open_to_work_flag': True,
 'profile_views_received_30d': 23,
 'applications_submitted_30d': 2,
 'recruiter_response_rate': 0.34,
 'avg_response_time_hours': 177.8,
 'skill_assessment_scores': {'NLP': 38.8,
  'Image Classification': 64.8,
  'Fine-tuning LLMs': 41.6,
  'Speech Recognition': 53.7},
 'connection_count': 356,
 'endorsements_received': 35,
 'notice_period_days': 60,
 'expected_salary_range_inr_lpa': {'min': 18.7, 'max': 36.1},
 'preferred_work_mode': 'onsite',
 'willing_to_relocate': False,
 'github_activity_score': 9.2,
 'search_appearance_30d': 249,
 'saved_by_recruiters_30d': 4,
 'interview_completion_rate': 0.71,
 'offer_acceptance_rate': 0.58,
 'verified_email': True,
 'verified_phone': True,
 'linkedin_connected': False}

In [222]:
candidates[0]["skills"]

[{'name': 'Tailwind',
  'proficiency': 'intermediate',
  'endorsements': 3,
  'duration_months': 13},
 {'name': 'NLP',
  'proficiency': 'advanced',
  'endorsements': 37,
  'duration_months': 26},
 {'name': 'Image Classification',
  'proficiency': 'advanced',
  'endorsements': 7,
  'duration_months': 40},
 {'name': 'Fine-tuning LLMs',
  'proficiency': 'advanced',
  'endorsements': 21,
  'duration_months': 36},
 {'name': 'Weights & Biases',
  'proficiency': 'intermediate',
  'endorsements': 13,
  'duration_months': 30},
 {'name': 'Speech Recognition',
  'proficiency': 'advanced',
  'endorsements': 52,
  'duration_months': 33},
 {'name': 'Photoshop',
  'proficiency': 'intermediate',
  'endorsements': 8,
  'duration_months': 24},
 {'name': 'TTS',
  'proficiency': 'advanced',
  'endorsements': 56,
  'duration_months': 60},
 {'name': 'LoRA',
  'proficiency': 'intermediate',
  'endorsements': 0,
  'duration_months': 28},
 {'name': 'Apache Beam',
  'proficiency': 'intermediate',
  'endorsements': 4,
  'duration_months': 9},
 {'name': 'AWS',
  'proficiency': 'beginner',
  'endorsements': 5,
  'duration_months': 8},
 {'name': 'Flask',
  'proficiency': 'beginner',
  'endorsements': 15,
  'duration_months': 15},
 {'name': 'BentoML',
  'proficiency': 'intermediate',
  'endorsements': 3,
  'duration_months': 36},
 {'name': 'Milvus',
  'proficiency': 'advanced',
  'endorsements': 40,
  'duration_months': 35},
 {'name': 'GANs',
  'proficiency': 'advanced',
  'endorsements': 12,
  'duration_months': 19},
 {'name': 'Statistical Modeling',
  'proficiency': 'intermediate',
  'endorsements': 9,
  'duration_months': 8},
 {'name': 'GCP',
  'proficiency': 'beginner',
  'endorsements': 7,
  'duration_months': 2}]

In [223]:
candidates[0]["career_history"][0]

{'company': 'Mindtree',
 'title': 'Backend Engineer',
 'start_date': '2024-03-08',
 'end_date': None,
 'duration_months': 27,
 'is_current': True,
 'industry': 'IT Services',
 'company_size': '10001+',
 'description': 'Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.'}

In [224]:
import pandas as pd

sample = pd.read_csv("sample_submission.csv")
sample.head()

,candidate_id,rank,score,reasoning
0,CAND_0004989,1,0.992,HR Manager with 6.1 yrs; 9 AI core skills; res...
1,CAND_0001195,2,0.984,HR Manager with 8.7 yrs; 9 AI core skills; res...
2,CAND_0003114,3,0.976,ML Engineer with 6.4 yrs; 4 AI core skills; re...
3,CAND_0000339,4,0.968,Content Writer with 8.3 yrs; 8 AI core skills;...
4,CAND_0001082,5,0.960,HR Manager with 5.0 yrs; 8 AI core skills; res...

In [225]:
from collections import Counter

titles = []

for c in candidates:
    title = c["profile"].get("current_title", "")
    titles.append(title)

Counter(titles).most_common(30)

[('Business Analyst', 5833),
 ('HR Manager', 5830),
 ('Mechanical Engineer', 5791),
 ('Accountant', 5764),
 ('Project Manager', 5754),
 ('Customer Support', 5750),
 ('Operations Manager', 5744),
 ('Content Writer', 5727),
 ('Sales Executive', 5713),
 ('Civil Engineer', 5702),
 ('Graphic Designer', 5689),
 ('Marketing Manager', 5524),
 ('Software Engineer', 3450),
 ('Full Stack Developer', 2873),
 ('Cloud Engineer', 2836),
 ('Java Developer', 2809),
 ('.NET Developer', 2788),
 ('DevOps Engineer', 2787),
 ('Mobile Developer', 2757),
 ('Frontend Engineer', 2738),
 ('QA Engineer', 2682),
 ('Analytics Engineer', 764),
 ('Data Engineer', 744),
 ('Data Analyst', 728),
 ('Backend Engineer', 704),
 ('Senior Data Engineer', 687),
 ('Senior Software Engineer', 653),
 ('ML Engineer', 167),
 ('AI Research Engineer', 153),
 ('Data Scientist', 145)]

In [226]:
industries = []

for c in candidates:
    industries.append(
        c["profile"].get("current_industry", "")
    )

Counter(industries).most_common(20)

[('IT Services', 29881),
 ('Software', 22417),
 ('Manufacturing', 22305),
 ('Conglomerate', 7571),
 ('Paper Products', 7467),
 ('Fintech', 2808),
 ('Food Delivery', 2514),
 ('E-commerce', 1529),
 ('Consulting', 1274),
 ('EdTech', 610),
 ('SaaS', 328),
 ('AI/ML', 278),
 ('AdTech', 172),
 ('Transportation', 162),
 ('Insurance Tech', 155),
 ('Gaming', 149),
 ('HealthTech', 147),
 ('HealthTech AI', 68),
 ('Conversational AI', 62),
 ('AI Services', 42)]

In [227]:
import pandas as pd

years = [
    c["profile"].get("years_of_experience", 0)
    for c in candidates
]

pd.Series(years).describe()

count    100000.000000
mean          7.166319
std           3.824551
min           1.000000
25%           3.900000
50%           6.800000
75%           9.900000
max          16.900000
dtype: float64

In [228]:
candidates[0]["education"]

[{'institution': 'Lovely Professional University',
  'degree': 'B.E.',
  'field_of_study': 'Computer Science',
  'start_year': 2017,
  'end_year': 2020,
  'grade': '8.24 CGPA',
  'tier': 'tier_3'}]

In [229]:
candidates[0]["certifications"]

[]

In [230]:
candidates[0]["languages"]

[{'language': 'English', 'proficiency': 'professional'},
 {'language': 'Hindi', 'proficiency': 'conversational'}]

In [231]:
from collections import Counter

skill_counter = Counter()

for c in candidates:
    for skill in c["skills"]:
        skill_counter[skill["name"]] += 1

skill_counter.most_common(100)

[('HTML', 12246),
 ('Databricks', 12244),
 ('Redux', 12222),
 ('Terraform', 12187),
 ('Angular', 12173),
 ('Figma', 12157),
 ('Salesforce CRM', 12157),
 ('Vue.js', 12142),
 ('Sales', 12138),
 ('Accounting', 12136),
 ('Agile', 12135),
 ('Kafka', 12114),
 ('Excel', 12109),
 ('BigQuery', 12108),
 ('CI/CD', 12108),
 ('Project Management', 12106),
 ('Airflow', 12105),
 ('AWS', 12104),
 ('Flask', 12104),
 ('Scrum', 12083),
 ('Illustrator', 12072),
 ('Kubernetes', 12071),
 ('ETL', 12068),
 ('CSS', 12065),
 ('Docker', 12062),
 ('Next.js', 12058),
 ('Apache Beam', 12054),
 ('Java', 12049),
 ('Go', 12049),
 ('TypeScript', 12048),
 ('JavaScript', 12047),
 ('dbt', 12046),
 ('REST APIs', 12040),
 ('Spark', 12038),
 ('Marketing', 12037),
 ('Tally', 12030),
 ('GraphQL', 12027),
 ('Snowflake', 12027),
 ('Webpack', 12026),
 ('Six Sigma', 11991),
 ('SEO', 11990),
 ('SAP', 11989),
 ('GCP', 11983),
 ('PostgreSQL', 11983),
 ('Rust', 11960),
 ('Apache Flink', 11958),
 ('gRPC', 11957),
 ('Content Writing', 11948),
 ('SQL', 11935),
 ('Hadoop', 11931),
 ('Redis', 11928),
 ('Tailwind', 11917),
 ('Photoshop', 11917),
 ('FastAPI', 11917),
 ('Microservices', 11909),
 ('PowerPoint', 11908),
 ('Spring Boot', 11906),
 ('Data Pipelines', 11905),
 ('Django', 11899),
 ('MongoDB', 11841),
 ('Node.js', 11838),
 ('Azure', 11828),
 ('React', 11811),
 ('Hugging Face Transformers', 5163),
 ('LangChain', 5162),
 ('Information Retrieval', 5135),
 ('LLMs', 5094),
 ('Recommendation Systems', 5091),
 ('Semantic Search', 5087),
 ('Sentence Transformers', 5081),
 ('Embeddings', 5080),
 ('Vector Search', 5065),
 ('Prompt Engineering', 5062),
 ('Pinecone', 5062),
 ('FAISS', 5052),
 ('RAG', 4995),
 ('Fine-tuning LLMs', 4920),
 ('YOLO', 4827),
 ('GANs', 4815),
 ('Feature Engineering', 4809),
 ('OpenCV', 4803),
 ('ASR', 4788),
 ('Image Classification', 4761),
 ('Computer Vision', 4755),
 ('Speech Recognition', 4744),
 ('CNN', 4740),
 ('Kubeflow', 4730),
 ('MLOps', 4727),
 ('BentoML', 4726),
 ('Data Science', 4708),
 ('Reinforcement Learning', 4708),
 ('Object Detection', 4705),
 ('Diffusion Models', 4701),
 ('MLflow', 4691),
 ('Time Series', 4686),
 ('Weights & Biases', 4685),
 ('Forecasting', 4676),
 ('TTS', 4669),
 ('Statistical Modeling', 4634),
 ('QLoRA', 1401)]

In [232]:
for i in range(5):
    print("=" * 80)
    print(candidates[i]["profile"]["current_title"])
    print()
    print(candidates[i]["career_history"][0]["description"])

================================================================================
Backend Engineer

Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.
================================================================================
Operations Manager

Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise.
================================================================================
Customer Support

Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-craft, Excel modeling, executive communication). Recent project work involved AI-strategy advisory but my own technical depth in AI is limited.
================================================================================
Marketing Manager

Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up.
================================================================================
Accountant

Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-craft, Excel modeling, executive communication). Recent project work involved AI-strategy advisory but my own technical depth in AI is limited.

In [233]:
skill_counter.most_common(100)

[('HTML', 12246),
 ('Databricks', 12244),
 ('Redux', 12222),
 ('Terraform', 12187),
 ('Angular', 12173),
 ('Figma', 12157),
 ('Salesforce CRM', 12157),
 ('Vue.js', 12142),
 ('Sales', 12138),
 ('Accounting', 12136),
 ('Agile', 12135),
 ('Kafka', 12114),
 ('Excel', 12109),
 ('BigQuery', 12108),
 ('CI/CD', 12108),
 ('Project Management', 12106),
 ('Airflow', 12105),
 ('AWS', 12104),
 ('Flask', 12104),
 ('Scrum', 12083),
 ('Illustrator', 12072),
 ('Kubernetes', 12071),
 ('ETL', 12068),
 ('CSS', 12065),
 ('Docker', 12062),
 ('Next.js', 12058),
 ('Apache Beam', 12054),
 ('Java', 12049),
 ('Go', 12049),
 ('TypeScript', 12048),
 ('JavaScript', 12047),
 ('dbt', 12046),
 ('REST APIs', 12040),
 ('Spark', 12038),
 ('Marketing', 12037),
 ('Tally', 12030),
 ('GraphQL', 12027),
 ('Snowflake', 12027),
 ('Webpack', 12026),
 ('Six Sigma', 11991),
 ('SEO', 11990),
 ('SAP', 11989),
 ('GCP', 11983),
 ('PostgreSQL', 11983),
 ('Rust', 11960),
 ('Apache Flink', 11958),
 ('gRPC', 11957),
 ('Content Writing', 11948),
 ('SQL', 11935),
 ('Hadoop', 11931),
 ('Redis', 11928),
 ('Tailwind', 11917),
 ('Photoshop', 11917),
 ('FastAPI', 11917),
 ('Microservices', 11909),
 ('PowerPoint', 11908),
 ('Spring Boot', 11906),
 ('Data Pipelines', 11905),
 ('Django', 11899),
 ('MongoDB', 11841),
 ('Node.js', 11838),
 ('Azure', 11828),
 ('React', 11811),
 ('Hugging Face Transformers', 5163),
 ('LangChain', 5162),
 ('Information Retrieval', 5135),
 ('LLMs', 5094),
 ('Recommendation Systems', 5091),
 ('Semantic Search', 5087),
 ('Sentence Transformers', 5081),
 ('Embeddings', 5080),
 ('Vector Search', 5065),
 ('Prompt Engineering', 5062),
 ('Pinecone', 5062),
 ('FAISS', 5052),
 ('RAG', 4995),
 ('Fine-tuning LLMs', 4920),
 ('YOLO', 4827),
 ('GANs', 4815),
 ('Feature Engineering', 4809),
 ('OpenCV', 4803),
 ('ASR', 4788),
 ('Image Classification', 4761),
 ('Computer Vision', 4755),
 ('Speech Recognition', 4744),
 ('CNN', 4740),
 ('Kubeflow', 4730),
 ('MLOps', 4727),
 ('BentoML', 4726),
 ('Data Science', 4708),
 ('Reinforcement Learning', 4708),
 ('Object Detection', 4705),
 ('Diffusion Models', 4701),
 ('MLflow', 4691),
 ('Time Series', 4686),
 ('Weights & Biases', 4685),
 ('Forecasting', 4676),
 ('TTS', 4669),
 ('Statistical Modeling', 4634),
 ('QLoRA', 1401)]

In [ ]:
interesting_titles = [
    "ML Engineer",
    "AI Research Engineer",
    "Data Scientist",
    "Data Engineer",
    "Analytics Engineer",
    "Backend Engineer"
]

for c in candidates:
    if c["profile"]["current_title"] in interesting_titles:
        print("="*100)
        print(c["profile"]["current_title"])
        print(c["profile"]["headline"])
        print()
        print(c["profile"]["summary"][:1000])
        break

====================================================================================================
Backend Engineer
Backend Engineer | SQL, Spark, Cloud

Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.

In [235]:
# ==========================
# Candidate Ranking V1
# ==========================

In [236]:
retrieval_skills = {
    "Information Retrieval",
    "Recommendation Systems",
    "Semantic Search",
    "Sentence Transformers",
    "Embeddings",
    "Vector Search",
    "Pinecone",
    "FAISS",
    "RAG",
    "Milvus",
    "retrieval",
    "ranking",
    "recommendation",
    "semantic search",
    "vector search",
    "embeddings",
    "faiss",
    "pinecone",
    "milvus",
    "hybrid retrieval",
    "learning-to-rank",
    "bm25"
}

llm_skills = {
    "LLMs",
    "Fine-tuning LLMs",
    "Prompt Engineering",
    "LangChain",
    "QLoRA",
    "Hugging Face Transformers"
}

production_ml_skills = {
    "MLOps",
    "MLflow",
    "Kubeflow",
    "BentoML",
    "Weights & Biases",
    "Feature Engineering"
}

engineering_skills = {
    "Python",
    "Docker",
    "Kubernetes",
    "AWS",
    "GCP",
    "FastAPI",
    "Flask",
    "Kafka",
    "Microservices"
}

negative_skills = {
    "YOLO",
    "OpenCV",
    "Computer Vision",
    "Object Detection",
    "Image Classification",
    "CNN",
    "Speech Recognition",
    "ASR",
    "TTS"
}

In [237]:
title_scores = {

    # Elite
    "Senior Machine Learning Engineer": 60,
    "Staff Machine Learning Engineer": 60,
    "Senior NLP Engineer": 55,
    "Senior AI Engineer": 55,
    "Lead AI Engineer": 55,
    "Recommendation Systems Engineer": 50,
    "Search Engineer": 50,
    "AI Engineer": 45,
    "Applied ML Engineer": 45,
    "Senior Data Scientist": 40,

    # Strong
    "ML Engineer": 30,
    "AI Research Engineer": 28,
    "Data Scientist": 25,
    "Analytics Engineer": 20,
    "Data Engineer": 18,
    "Backend Engineer": 15,

    # Existing
    "Senior Data Engineer": 15,
    "Senior Software Engineer": 12,
    "Software Engineer": 10
}

In [238]:
negative_titles = {
    "HR Manager",
    "Content Writer",
    "Marketing Manager",
    "Sales Executive",
    "Graphic Designer",
    "Operations Manager",
    "Accountant",
    "Customer Support",
    "Business Analyst",
    "Mechanical Engineer",
    "Civil Engineer"
}

tourist_keywords = [
    "online courses",
    "langchain",
    "openai api",
    "grow my ai",
    "exploring ai",
    "ai enthusiast",
    "side projects"
]

product_industries = {
    "Software",
    "SaaS",
    "AI/ML",
    "Fintech",
    "Food Delivery",
    "E-commerce"
}

In [239]:
evaluation_terms = [
    "evaluation",
    "eval",
    "offline benchmark",
    "a/b",
    "ndcg",
    "mrr",
    "map"
]

In [240]:
from docx import Document

doc = Document("job_description.docx")

job_text = "\n".join(
    paragraph.text
    for paragraph in doc.paragraphs
)

print(job_text[:2000])

Job Description: Senior AI Engineer — Founding Team
Company: Redrob AI (Series A AI-native talent intelligence platform)
Location: Pune/Noida, India (Hybrid — flexible cadence) | Open to relocation candidates from Tier-1 Indian cities
Employment Type: Full-time
Experience Required: 5–9 years (see "what we mean by this" below)

Let's be honest about this role
We're going to write this JD differently from most. We're a Series A company that just raised our round and we're building a new AI Engineering org from scratch. This is the kind of role where the JD changes every six months because the company changes every six months. So instead of pretending we have a fixed checklist, we're going to tell you what we actually need and what we've gotten wrong before.
If you've spent your career at Google or Meta and you want a well-scoped role with a defined ladder, this isn't it.
If you've spent your career bouncing between early-stage startups and you want to "just code" without having to think about product or recruiter workflows or eval frameworks, this also isn't it.
We need someone who is simultaneously comfortable with two things that sound contradictory:
Deep technical depth in modern ML systems — embeddings, retrieval, ranking, LLMs, fine-tuning.
Scrappy product-engineering attitude — willing to ship a working ranker in a week even if the underlying ML is "obviously suboptimal," because we need to learn from real users before we know what to actually optimize for.
These are not contradictory in real life. They feel contradictory because of how engineering culture sorted itself into "researcher" vs "shipper" archetypes. We need both modes available in the same person, and we'd rather you tilt slightly toward shipper than toward researcher.

What you'd actually be doing
The high-level mandate: own the intelligence layer of Redrob's product. That means the ranking, retrieval, and matching systems that decide what recruiters see when they search for candidates and what can

In [241]:
candidate_documents = []

for candidate in candidates:

    profile = candidate["profile"]

    headline = profile.get("headline", "")
    summary = profile.get("summary", "")
    title = profile.get("current_title", "")
    industry = profile.get("current_industry", "")

    skills = " ".join(
        skill["name"]
        for skill in candidate["skills"]
    )

    history = " ".join(
        job.get("description", "")
        for job in candidate["career_history"]
    )

    document = " ".join([
        title,
        headline,
        summary,
        skills,
        history,
        industry
    ])

    candidate_documents.append(document.lower())

In [242]:
print(candidate_documents[0][:800])

backend engineer backend engineer | sql, spark, cloud software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. i'm a backend/data hybrid — spark, airflow, sql warehouses are home territory; i'm building competence on the ml side. my toolkit is solid on the data engineering side — python, sql, spark, airflow, warehouse design — and i've completed a couple of self-directed ml projects (kaggle competitions, side projects fine-tuning small models). interested in transitioning toward more ai/ml-focused work, ideally at a company where i can leverage my existing data-infra skills while learning modern ml practice. tailwind nlp image classification fine-tuning llms weights & biases speech recognition photoshop tts lora apach

In [243]:
job_text = """
Senior AI Engineer

Building ranking systems
retrieval
embeddings
vector databases
hybrid retrieval
semantic search
Python
LLMs
fine tuning
recommendation systems
evaluation
NDCG
MRR
MAP
BM25
FAISS
Pinecone
Qdrant
Milvus
Elasticsearch
production ML
product engineering
"""

In [244]:
pip install rank_bm25

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: rank_bm25 in c:\users\manya\appdata\roaming\python\python313\site-packages (0.2.2)
Requirement already satisfied: numpy in c:\users\manya\appdata\roaming\python\python313\site-packages (from rank_bm25) (2.1.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [245]:
from rank_bm25 import BM25Okapi

In [246]:
tokenized_docs = [
    doc.split()
    for doc in candidate_documents
]

bm25 = BM25Okapi(tokenized_docs)

query = job_text.lower().split()

bm25_scores = bm25.get_scores(query)

In [247]:
print(len(bm25_scores))

100000

In [248]:
print(max(bm25_scores))
print(min(bm25_scores))

69.96797063646801
1.2774611246876635

In [249]:
top10 = sorted(
    enumerate(bm25_scores),
    key=lambda x: x[1],
    reverse=True
)[:10]

for idx, score in top10:

    c = candidates[idx]

    print("="*80)
    print(c["candidate_id"])
    print(c["profile"]["current_title"])
    print(round(score,2))

================================================================================
CAND_0081846
Lead AI Engineer
69.97
================================================================================
CAND_0039754
Senior Applied Scientist
68.19
================================================================================
CAND_0026532
Recommendation Systems Engineer
66.61
================================================================================
CAND_0018499
Senior Machine Learning Engineer
65.17
================================================================================
CAND_0088025
Staff Machine Learning Engineer
64.2
================================================================================
CAND_0061265
Recommendation Systems Engineer
63.91
================================================================================
CAND_0070398
Machine Learning Engineer
63.21
================================================================================
CAND_0036184
Recommendation Systems Engineer
62.77
================================================================================
CAND_0046064
Senior NLP Engineer
62.45
================================================================================
CAND_0086151
Recommendation Systems Engineer
61.34

In [250]:
import numpy as np

bm25_scores = np.array(bm25_scores)

bm25_scores = (
    bm25_scores - bm25_scores.min()
) / (
    bm25_scores.max() - bm25_scores.min()
)

In [251]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [252]:
documents = [job_text.lower()] + candidate_documents

vectorizer = TfidfVectorizer(
    stop_words="english"
)

tfidf_matrix = vectorizer.fit_transform(documents)

In [253]:
print(tfidf_matrix.shape)

(100001, 1143)

In [254]:
job_vector = tfidf_matrix[0]

candidate_vectors = tfidf_matrix[1:]

tfidf_scores = cosine_similarity(
    job_vector,
    candidate_vectors
).flatten()

In [255]:
print(len(tfidf_scores))

100000

In [256]:
tfidf_scores = (
    tfidf_scores - tfidf_scores.min()
) / (
    tfidf_scores.max() - tfidf_scores.min()
)

In [257]:
top10 = np.argsort(tfidf_scores)[::-1][:10]

for idx in top10:

    c = candidates[idx]

    print("="*80)
    print(c["candidate_id"])
    print(c["profile"]["current_title"])
    print(round(tfidf_scores[idx], 3))

================================================================================
CAND_0081846
Lead AI Engineer
1.0
================================================================================
CAND_0039754
Senior Applied Scientist
0.944
================================================================================
CAND_0018499
Senior Machine Learning Engineer
0.839
================================================================================
CAND_0041611
Staff Machine Learning Engineer
0.815
================================================================================
CAND_0055905
Senior Machine Learning Engineer
0.808
================================================================================
CAND_0046064
Senior NLP Engineer
0.777
================================================================================
CAND_0085195
Mechanical Engineer
0.771
================================================================================
CAND_0014439
Civil Engineer
0.765
================================================================================
CAND_0015051
Marketing Manager
0.759
================================================================================
CAND_0099670
Project Manager
0.758

In [258]:
def consistency_penalty(candidate):

    penalty = 0

    profile = candidate["profile"]

    exp = profile.get("years_of_experience", 0)

    # ---------------------------------------------------
    # 1. Claimed experience vs career history
    # ---------------------------------------------------
    total_months = sum(
        job.get("duration_months", 0)
        for job in candidate["career_history"]
    )

    actual_exp = total_months / 12

    if abs(actual_exp - exp) > 2:
        penalty += 20

    # ---------------------------------------------------
    # 2. Skill duration cannot greatly exceed experience
    # ---------------------------------------------------
    impossible_skills = 0

    for skill in candidate["skills"]:

        years = skill.get("duration_months", 0) / 12

        if years > exp + 1:
            impossible_skills += 1

    penalty += impossible_skills * 5

    # ---------------------------------------------------
    # 3. Too many expert skills is suspicious
    # ---------------------------------------------------
    expert_count = sum(
        skill.get("proficiency", "").lower() == "expert"
        for skill in candidate["skills"]
    )

    if expert_count > 8:
        penalty += (expert_count - 8) * 2

    # ---------------------------------------------------
    # 4. Senior title but beginner summary
    # ---------------------------------------------------
    title = profile.get("current_title", "").lower()
    summary = profile.get("summary", "").lower()

    if "senior" in title:

        beginner_phrases = [
            "online courses",
            "learning ai",
            "building competence",
            "transitioning toward ai",
            "grow my ai",
            "exploring ai",
            "new to ai"
        ]

        if any(p in summary for p in beginner_phrases):
            penalty += 25

    # ---------------------------------------------------
    # 5. Recommendation/Search title without retrieval terms
    # ---------------------------------------------------
    if any(
        word in title
        for word in [
            "recommendation",
            "search",
            "nlp",
            "machine learning",
            "ai engineer"
        ]
    ):

        career_text = " ".join(
            job.get("description", "")
            for job in candidate["career_history"]
        ).lower()

        retrieval_terms = [
            "retrieval",
            "ranking",
            "recommendation",
            "embeddings",
            "faiss",
            "pinecone",
            "semantic search",
            "vector search",
            "bm25",
            "learning-to-rank",
            "llm",
            "transformer"
        ]

        hits = sum(
            term in career_text
            for term in retrieval_terms
        )

        if hits < 2:
            penalty += 20

    return penalty

In [259]:
def score_candidate(candidate):

    score = 0

    profile = candidate["profile"]

    # -------------------------
    # Title
    # -------------------------
    title = profile.get("current_title", "")
    score += title_scores.get(title, 0)

    if title in negative_titles:
        score -= 30

    # -------------------------
    # Experience
    # -------------------------
    exp = profile.get("years_of_experience", 0)

    if 6 <= exp <= 8:
        score += 20
    elif 5 <= exp <= 9:
        score += 15
    elif 4 <= exp <= 10:
        score += 10
    elif exp > 12:
        score -= 10

    # -------------------------
    # Skills
    # -------------------------
    skills = {s["name"] for s in candidate["skills"]}

    score += 3 * len(skills & retrieval_skills)
    score += 3 * len(skills & llm_skills)
    score += 2 * len(skills & production_ml_skills)
    score += 1 * len(skills & engineering_skills)

    score -= 2 * len(skills & negative_skills)

    # -------------------------
    # AI Tourist Penalty
    # -------------------------
    summary = profile.get("summary", "").lower()

    matches = sum(
        kw in summary
        for kw in tourist_keywords
    )

    if matches >= 3:
        score -= 20

    # -------------------------
    # Product Company Boost
    # -------------------------
    product_count = 0

    for job in candidate["career_history"]:
        if job.get("industry") in product_industries:
            product_count += 1

    score += product_count * 2

    # -------------------------
    # Retrieval/Ranking Experience
    # -------------------------
    career_text = " ".join(
        job.get("description", "")
        for job in candidate["career_history"]
    ).lower()

    #Evaluation
    for term in evaluation_terms:
        if term in career_text:
            score += 10


    important_terms = [
        "recommendation",
        "retrieval",
        "ranking",
        "search",
        "matching",
        "relevance"
    ]

    for term in important_terms:
        if term in career_text:
            score += 8

    return score

In [260]:
def behavioral_score(candidate):

    signals = candidate["redrob_signals"]

    score = 0

    if signals["open_to_work_flag"]:
        score += 10

    score += 6 * signals["recruiter_response_rate"]

    score += 8 * signals["interview_completion_rate"]

    score += min(
        signals["saved_by_recruiters_30d"],
        10
    )

    notice = signals["notice_period_days"]

    if notice <= 30:
        score += 5
    elif notice <= 60:
        score += 2

    return score

In [261]:
print("Rule score range:")
rule_scores = [score_candidate(c) for c in candidates]
print(min(rule_scores), max(rule_scores))

print("Behavior score range:")
behavior_scores = [behavioral_score(c) for c in candidates]
print(min(behavior_scores), max(behavior_scores))

print("Penalty range:")
penalties = [consistency_penalty(c) for c in candidates]
print(min(penalties), max(penalties))

print("BM25 range:")
print(min(bm25_scores), max(bm25_scores))

print("TF-IDF range:")
print(min(tfidf_scores), max(tfidf_scores))

Rule score range:
-42 190
Behavior score range:
2.7800000000000002 38.06
Penalty range:
0 77
BM25 range:
0.0 1.0
TF-IDF range:
0.0 1.0

In [262]:
def final_score(candidate, bm25, tfidf):

    rule = score_candidate(candidate)

    behavior = behavioral_score(candidate)

    penalty = consistency_penalty(candidate)

    score = (
        rule
        + behavior
        + 35 * bm25
        + 25 * tfidf
        - penalty
    )

    return score

In [263]:
results = []

for i, candidate in enumerate(candidates):

    score = final_score(
        candidate,
        bm25_scores[i],
        tfidf_scores[i]
    )

    results.append(
        {
            "candidate_id": candidate["candidate_id"],
            "score": score,
            "candidate": candidate
        }
    )

In [264]:
results = sorted(
    results,
    key=lambda x: x["score"],
    reverse=True
)

In [265]:
top100 = results[:100]

In [266]:
def build_reasoning(candidate):

    profile = candidate["profile"]

    signals = candidate["redrob_signals"]

    skills = {
        s["name"]
        for s in candidate["skills"]
    }

    reasons = []

    # Title
    title = profile["current_title"]

    if title in title_scores:
        reasons.append(title)

    # Experience
    exp = profile["years_of_experience"]

    reasons.append(f"{exp:.1f} yrs")

    # Core AI skills
    core = len(skills & retrieval_skills)

    if core:
        reasons.append(f"{core} retrieval skills")

    llm = len(skills & llm_skills)

    if llm:
        reasons.append(f"{llm} LLM skills")

    # Behavioral
    if signals["open_to_work_flag"]:
        reasons.append("Open to work")

    if signals["recruiter_response_rate"] > 0.7:
        reasons.append("High recruiter response")

    if signals["interview_completion_rate"] > 0.8:
        reasons.append("Strong interview completion")

    return ", ".join(reasons)

In [267]:
import pandas as pd

submission = pd.DataFrame({

    "candidate_id": [
        r["candidate_id"]
        for r in top100
    ],

    "rank": range(1,101),

    "score": [
        round(r["score"],6)
        for r in top100
    ],

    "reasoning": [
        build_reasoning(r["candidate"])
        for r in top100
    ]

})

In [268]:
submission.head()

print(submission.columns)

print(len(submission))

print(submission["rank"].min())

print(submission["rank"].max())

Index(['candidate_id', 'rank', 'score', 'reasoning'], dtype='object')
100
1
100

In [269]:
submission.to_csv(
    "submission.csv",
    index=False
)